platform :ios, ‘8.1’

use_frameworks!

target ‘TestCategory’ do

pod 'LXRouter’,:git => 'https://github.com/livesxu/LXRouter.git'
pod 'LXShowLoading’,:git => 'https://github.com/livesxu/LXShowLoading.git'
pod 'LXAlertBlock’,:git => 'https://github.com/livesxu/LXAlertBlock.git'
pod 'TableViewSimple’,:git => 'https://github.com/livesxu/TableViewSimple.git'
pod 'CustomPickView’,:git => 'https://github.com/livesxu/CustomPickView.git'
pod 'LXAOPTask’,:git => 'https://github.com/livesxu/LXAOPTask.git'
pod 'LXScrollLoopViewController’,:git => 'https://github.com/livesxu/LXScrollLoopViewController.git'
pod 'LXPageViewController’,:git => 'https://github.com/livesxu/LXPageViewController.git'
pod 'LXCategory’,:git => 'https://github.com/livesxu/LXCategory.git'

end
